### PR TITLE
Building an API using a Relational Database(Knex Migrations)

### PR DESCRIPTION
**Pull request by TevvinStrong**

### CODE REVIEW

**Comment by TevvinStrong** [comment]
@jeffyjkang I know I could have given my migration file a better name any suggestions? when it comes to naming migration files in a way they won't be confusing?

**Comment by TevvinStrong** [comment]
@jeffyjkang Actually I figured this out before my last change I was adding the student's table inside my cohort migration. Although I was able to create the student's table I believe the correct way to do this is by implementing a new migration for students with the correct schema. Let me know if I'm correct on this.

**Comment by TevvinStrong** [comment]
@jeffyjkang Migrations and seeds complete. Will implement endpoints tomorrow.

**Review by jeffyjkang — APPROVED** [review]
great work so far, nice job on the async functions for the tables, i dont think a lot of people would have done it this way.

**Pull request merged**
